services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:
      - ./.env
    networks:
      - app_network

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application"
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network: