services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application"
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}