services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:
      - ./.env
    restart: always

  web:
    build: .
    volumes:
      - static_volume:/mysite/blog/static
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  
  nginx:
    image: nginx:1.25.5
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/mysite/blog/static:ro
    depends_on:
      - web
    restart: always


volumes:
  postgres_data:
  static_volume:
  media_volume: